---
title: "Geocoding"
output: html_document
date: "2023-10-17"
---



# Library

```{r}

library(tidyverse)
library(usmap)
library(tidycensus)
library(tigris)
library(tidygeocoder)
library(gganimate)

```


# Read in data

```{r}
 
sites <- read_csv("/Users/markow/Dropbox/Git/Competition/data_processed/sites_geocoded.csv") %>% 
  select(`BHCMIS ID`:`Site ZIP Code`, Zip)

```


# Code

```{r}
tbcoded <- sites


coded <-  geo(street = tbcoded[c(1:10000),]$`Site Street Address`, 
             city = tbcoded[c(1:10000),]$`Site City`, 
             state = tbcoded[c(1:10000),]$`Site State`, 
             method = "census", 
             full_results = TRUE)
  
coded <- cbind(coded, geo(street = tbcoded[c(1:10000),]$`Site Street Address 3`, 
             city = tbcoded[c(1:10000),]$`Site City`, 
             state = tbcoded[c(1:10000),]$`Site State`, 
             method = "census", 
             full_results = TRUE))
  
coded <- cbind(coded,  geo(street = tbcoded[c(1:10000),]$`Site Street Address`, 
             city = tbcoded[c(1:10000),]$`Site Street Address 2`, 
             method = "census", 
             full_results = TRUE))



for (g in 1:17){
  print (g)
 coded2 <-  geo(street = tbcoded[c((1 + g*10000):((g+1)*10000)),]$`Site Street Address`, 
             city = tbcoded[c((1 + g*10000):((g+1)*10000)),]$`Site City`, 
             state = tbcoded[c((1 + g*10000):((g+1)*10000)),]$`Site State`, 
             method = "census", 
             full_results = TRUE)
  
coded2 <- cbind(coded2, geo(street = tbcoded[c((1 + g*10000):((g+1)*10000)),]$`Site Street Address 3`, 
             city = tbcoded[c((1 + g*10000):((g+1)*10000)),]$`Site City`, 
             state = tbcoded[c((1 + g*10000):((g+1)*10000)),]$`Site State`, 
             method = "census", 
             full_results = TRUE))
  
coded2 <- cbind(coded2,  geo(street = tbcoded[c((1 + g*10000):((g+1)*10000)),]$`Site Street Address`, 
             city = tbcoded[c((1 + g*10000):((g+1)*10000)),]$`Site Street Address 2`, 
             method = "census", 
             full_results = TRUE)) 
coded <- rbind(coded, coded2)
}



 coded2 <-  geo(street = tbcoded[c(180001:188381),]$`Site Street Address`, 
             city = tbcoded[c(180001:188381),]$`Site City`, 
             state = tbcoded[c(180001:188381),]$`Site State`, 
             method = "census", 
             full_results = TRUE)
  
coded2 <- cbind(coded2, geo(street = tbcoded[c(180001:188381),]$`Site Street Address 3`, 
             city = tbcoded[c(180001:188381),]$`Site City`, 
             state = tbcoded[c(180001:188381),]$`Site State`, 
             method = "census", 
             full_results = TRUE))
  
coded2 <- cbind(coded2,  geo(street = tbcoded[c(180001:188381),]$`Site Street Address`, 
             city = tbcoded[c(180001:188381),]$`Site Street Address 2`, 
             method = "census", 
             full_results = TRUE)) 
coded <- rbind(coded, coded2)
```


```{r}

sites.coded <- cbind(sites, coded[,c(4,5, 10, 16, 17, 22, 27, 28, 33)]) 

#write.csv(x = sites.coded, file = "/Users/jhm65/Dropbox/Git/Allocation/data_processed/sites_halfway_geocoded.csv", row.names = FALSE)
#
#sites.coded <- read.csv("/Users/markow/Dropbox/Git/Allocation/data_processed/sites_halfway_geocoded.csv", colClasses = "character")


```


## Next Cleaning Steps

Need to finish the geocoding
```{r}
tbcoded <- sites.coded %>% 
  filter(is.na(lat) & is.na(lat.1) & is.na(lat.2)) %>% 
  mutate(add = paste(Site.Street.Address, Site.Street.Address.2, sep = ", "))


coded3 <- geo(address = tbcoded$add, 
             method = "census", 
             full_results = TRUE)




tbcoded <- sites.coded %>% 
  filter(is.na(lat) & is.na(lat.1) & is.na(lat.2)) %>% 
  mutate(add = paste(Site.Street.Address, Site.City, Site.State, sep = ", "))


coded4.1 <- geo(address = tbcoded[c(1:15000),]$add,
             method = "census", 
             full_results = TRUE)
coded4.2 <- geo(address = tbcoded[c(15001:37249),]$add,
             method = "census", 
             full_results = TRUE)

coded4 <- rbind(coded4.1, coded4.2)






tbcoded <- sites.coded %>% 
  filter(is.na(lat) & is.na(lat.1) & is.na(lat.2)) %>% 
  mutate(add = paste(Site.Street.Address.3, Site.City, Site.State, sep = ", "))

coded5 <- geo(address = tbcoded$add, 
             method = "census", 
             full_results = TRUE)



tbcoded <- sites.coded %>% 
  filter(is.na(lat) & is.na(lat.1) & is.na(lat.2)) %>% 
  mutate(add = paste(Site.Street.Address, Site.City, Site.State, Zip, sep = ", "))


coded6.1 <- geo(address = tbcoded[c(1:15000),]$add,
             method = "census", 
             full_results = TRUE)
coded6.2 <- geo(address = tbcoded[c(15001:37249),]$add,
             method = "census", 
             full_results = TRUE)

coded6 <- rbind(coded6.1, coded6.2)





#tbcoded <- cbind(tbcoded, coded3 %>% select(lat, long, matched_address))


  coded3 %>% select(lat, long, matched_address) %>% filter(!is.na(lat))
  coded4 %>% select(lat, long, matched_address) %>% filter(!is.na(lat))
  coded5 %>% select(lat, long, matched_address) %>% filter(!is.na(lat))
  coded6 %>% select(lat, long, matched_address) %>% filter(!is.na(lat))
  

  
  sites.coded %>% 
  filter(is.na(lat) & is.na(lat.1) & is.na(lat.2)) %>% 
  select(BHCMIS.ID:Zip) %>% 
  cbind(
  data.frame(coded3 %>% select(lat, long, matched_address), 
             coded4 %>% select(lat, long, matched_address), 
             coded5 %>% select(lat, long, matched_address), 
             coded6 %>% select(lat, long, matched_address)) %>% 
    mutate(lat = ifelse(!is.na(lat), lat, 
                        ifelse(is.na(lat) & !is.na(lat.1), lat.1, 
                               ifelse(is.na(lat) & is.na(lat.1), lat.2, 
                                      ifelse(is.na(lat) & is.na(lat.1) & is.na(lat.2), lat.3, NA)))),
           long = ifelse(!is.na(long), long, 
                        ifelse(is.na(long) & !is.na(long.1), long.1, 
                               ifelse(is.na(long) & is.na(long.1), long.2, 
                                      ifelse(is.na(long) & is.na(long.1) & is.na(long.2), long.3, NA))))) %>% 
    select(lat, long)) %>% 
    filter(is.na(lat))
```

## Merge Sets, make some more progress on coding

```{r}
  
sites.coded.almost <- rbind(sites.coded %>% 
  filter(!is.na(lat) | !is.na(lat.1) | !is.na(lat.2)) %>% 
   mutate(lat = ifelse(!is.na(lat), lat, 
                        ifelse(is.na(lat) & !is.na(lat.1), lat.1, 
                               ifelse(is.na(lat) & is.na(lat.1), lat.2, NA))),
           long = ifelse(!is.na(long), long, 
                        ifelse(is.na(long) & !is.na(long.1), long.1, 
                               ifelse(is.na(long) & is.na(long.1), long.2, NA)))) %>% 
  select(BHCMIS.ID:Zip, lat, long), 
  sites.coded %>% 
  filter(is.na(lat) & is.na(lat.1) & is.na(lat.2)) %>% 
  select(BHCMIS.ID:Zip) %>% 
  cbind(
  data.frame(coded3 %>% select(lat, long, matched_address), 
             coded4 %>% select(lat, long, matched_address), 
             coded5 %>% select(lat, long, matched_address), 
             coded6 %>% select(lat, long, matched_address)) %>% 
    mutate(lat = ifelse(!is.na(lat), lat, 
                        ifelse(is.na(lat) & !is.na(lat.1), lat.1, 
                               ifelse(is.na(lat) & is.na(lat.1) & !is.na(lat.2), lat.2, 
                                      ifelse(is.na(lat) & is.na(lat.1) & is.na(lat.2), lat.3, NA)))),
           long = ifelse(!is.na(long), long, 
                        ifelse(is.na(long) & !is.na(long.1), long.1, 
                               ifelse(is.na(long) & is.na(long.1) & !is.na(long.2), long.2, 
                                      ifelse(is.na(long) & is.na(long.1) & is.na(long.2), long.3, NA))))) %>% 
    select(lat, long)))


table(sites.coded.almost$Year, is.na(sites.coded.almost$lat))




tbcoded <- sites.coded.almost %>% 
  filter(is.na(lat)) %>% 
  mutate(add = paste(Site.Street.Address.3, Site.City, Site.State, Zip, sep = ", "))


coded7.1 <- geo(address = tbcoded[c(1:15000),]$add,
             method = "census", 
             full_results = TRUE)
coded7.2 <- geo(address = tbcoded[c(15001:nrow(tbcoded)),]$add,
             method = "census", 
             full_results = TRUE)

coded7 <- rbind(coded7.1, coded7.2)


coded7 %>% select(lat, long) %>% filter(!is.na(lat))


sites.coded.almost <- sites.coded.almost %>% 
  filter(!is.na(lat)) %>% 
  rbind(cbind(tbcoded %>% select(BHCMIS.ID:Zip), coded7 %>% select(lat, long) ))

table(sites.coded.almost$Year, is.na(sites.coded.almost$lat))


sites.coded.almost %>% 
  filter(is.na(lat))

```

## Final Coding and Cleaning - this takes a bit for some reason (~15 minutes)

```{r}

temp <- sites.coded.almost %>% 
  filter(is.na(lat)) %>% 
  select(BHCMIS.ID:Zip) #%>% filter(Site.City == "New Haven")

temp.coded <- geo(street = temp$Site.Street.Address, city = temp$Site.City, state = temp$Site.State, postalcode = temp$Zip, 
             method = "census", 
             full_results = TRUE)

sites.coded.almost.final <- sites.coded.almost %>% 
  filter(!is.na(lat)) %>% 
  rbind(cbind(temp %>% select(BHCMIS.ID:Zip), temp.coded %>% select(lat, long) ))

sites.coded.almost.final %>% 
  filter(is.na(lat))

```


## Do the rest by hand

```{r}


sites.coded.almost.final %>% 
  filter(is.na(lat))



ids <- unique(sites.coded.almost.final[is.na(sites.coded.almost.final$lat),]$BHCMIS.ID)


i <- 11

sites.coded.almost.final[sites.coded.almost.final$BHCMIS.ID == ids[i] ,] %>% 
  arrange(Site.Street.Address, Site.Street.Address.3)


## Set the function to do the replacement
sites.hand <- sites.coded.almost.final



geocoded.by.hand <- rbind(
  c("010070", "223 Portsea St", 41.297009, -72.933175), 
  c("010120", "256 Pleasant Street", 42.37918608231927, -72.51987353695388), 
  c("010120", "754 Alden Street", 42.1088790580001,	-72.543469919), 
  c("010120", "49-61 St. James Avenue", 42.1109923240001,	-72.573894579), 
  c("010130	", "404 Chestnut Street", 42.99110061868193, -71.46072106988214), 
  
  c("010170	", "100 Morrissey Boulevard", 42.314135433,	-71.046835546), 
  
  c("010170", "26-32 DEVINE WAY", 42.32863424664541, -71.05515641272427),
  c("010220", "330 Washington St STE 510", 41.54341840463725, -72.08685524806683),
  c("010220", "330 Washington St", 41.54341840463725, -72.08685524806683), 
  
  c("063450", "1302 Ease Main St.", 35.17894,	-103.7111), 
  c("063450", "2500 STATE HIGHWAY 197", 35.775749395185464, -107.25528853495592), 
  c("063450", "15 NAVARRE BLVD.", 35.40666753173769, -108.21977123125973), 
  c("063450", "5901 Herrera Dr", 35.6208746210265, -106.03880191961399), 
  c("063450", "1500 Idalia Rd. BLDG B", 35.309277645637316, -106.5847619137561),
  c("063450", "9837 U.S. HIGHWAY 550", 36.21614091513951, -107.46973343831986),
  c("063450", "9837 US Hwy 550", 36.21614091513951, -107.46973343831986), 
  c("063450", "903C N. 5TH STREET", 34.77319987842908, -106.05586680212811),
  
  c("034210", "65 Professional Pl", 39.334519549736946, -80.23605171737104), 
  c("034210", "Route 2 Box 525", 38.201179080116034, -80.11073497241968), 
  c("034210", "33-37 Main Street", 38.99445163947025, -80.22835502929739), 
  c("034210", "4 Northridge Dr Ste 118", 31.03034,	-96.48878), 
  c("034210", "1349 Shinnston Pike", 39.310036586282166, -80.35524854435509), 
  c("034210", "251 Marietta St.", 39.31101258711485, -80.35972084435507), 
  c("034210", "1 Panther Drive", 38.95940637387327, -80.9655121864181), 
  c("034210", "59 Ossia Rd", 38.58709289824125, -81.03424211553602), 
  c("034210", "271 Warrior Way", 38.28803371185271, -79.9311875570661), 
  c("034210", "HC 61 BOX 14", 38.65365850191463, -80.85373226999414), 
  c("034210", "113 5th St", 38.67162926512706, -80.77459062902577), 
  c("034210", "5917 Potomac Highlands Trl", 38.4257924795177, -79.82640227321187), 
  c("034210", "6404 Potomac Highlands Trail	", 38.42844245855573, -79.81775084622838), 
  c("034210", "PICKENS ROAD", 38.70022984122092, -80.20582362717253), 
  c("034210", "7576 Seneca Trail", 38.13604607040736, -80.21110438950197), 
  c("034210", "797 Clinic Dr", 38.600013813589264, -81.05184681553573), 
  c("034210", "15300 US Highway 33 W", 39.011104681395935, -80.7170536462147), 
  c("034210", "P.O. Box 70", 38.3303, -81.1726), 
  c("034210", "RR 1 Box 58", 39.18761	-80.38887), 
  c("034210", "78 Queens Alley Rd", 38.83911259426158, -80.34148008854655), 
  c("034210", "1176 Oil Creek Rd", 38.921861913351876, -80.50991956156115), 
  c("034210", "78 Jerry Toth Drive", 39.381798019320705, -80.31020753841317), 
  c("034210", "78 Jerry Toth Dr", 39.381798019320705, -80.31020753841317), 
  c("034210", "100 Carter Braxton Dr", 38.69471202530252, -80.66363537320564), 
  c("034210", "200 Jerry Burton Dr", 38.696015175525176, -80.66715488669742), 
  c("034210", "597 LIBERTY ST", 39.20406593698619, -80.39661007504624), 
  c("034210", "WEST MILFORD COMMUNITY HLTH CTR", 39.204262604422496, -80.39664970756594), 
  c("034210", "107 Staunton Dr", 39.022126447733676, -80.41844710203401), 
  c("034210", "358 Court Ave.", 39.03938440347651, -80.46234501552547), 
  c("034210", "Community Care of Weston", 39.022126447733676, -80.41844710203401), 
  c("034210", "TRI-COUNTY HEALTH CLINIC, INC.", 38.83911259426158, -80.34148008854655), 
  
  c("0452070", "127 Foothills Ave", 36.68128665673709, -85.12901440208728), 
  c("0452070", "204 King Dr", 36.7111846335348, -85.13558358324511), 
  c("0452070", "204 King Drive", 36.7111846335348, -85.13558358324511), 
  c("0452070", "65 High School Dr", 41.65198,	-70.28787	), 
  c("0452070", "360 KEEN STREET	", 36.785423353181685, -85.36904900208498), 
  c("0452070", "150 Generals Blvd", 37.84708511976141, -85.50607726501033), 
  c("0452070", "360 Keen Street", 36.785423353181685, -85.36904900208498), 
  c("0452070", "158 Col Casey Dr", 37.10657276192382, -85.33282500207784), 
  c("0452070", "158 Colonel Casey Dr.", 37.10657276192382, -85.33282500207784), 
  c("0452070", "322 Gen. John Adair Dr.", 37.10416701010006, -85.3251431875612), 
  c("0452070", "870 Indian Dr", 37.11148597761101, -85.3292415444056), 
  c("0452070", "Hardin Early College and Career Center Healthy Kids Clinic", 40.26334817628959, -76.67333560015184), 
  c("0452070", "2300 Nelson Dr", 37.73587346975672, -85.85399277297513), 
  c("0452070", "33 Eagle Lane", 37.55283347537022, -85.7288542443957),
  c("0452070", "33 Eagle Ln", 37.55283347537022, -85.7288542443957), 
  c("0452070", "1 Bearcat Dr", 38.024260198298656, -84.908567544385),
  c("0452070", "1 Bearcat Drive", 38.024260198298656, -84.908567544385), 
  c("0452070", "1150 Bypass N", 38.047392118605956, -84.91131338163227), 
  c("0452070", "1150 Bypass North	", 38.047392118605956, -84.91131338163227), 
  c("0452070", "1154 Bypass N", 38.048768157744, -84.91298280205663), 
  c("0452070", "1154 Bypass North", 38.048768157744, -84.91298280205663), 
  c("0452070", "200 Corporate Dr", 37.57810145497525, -85.23468757137867), 
  c("0452070", "1841 E. KY 70", 37.327044100991984, -84.9051530462533), 
  c("0452070", "Walnut Hill Healthy Kids Clinic", 37.28208256019851, -84.95859715311369), 
  c("0452070", "2819 N Highway 27", 36.7627876017049, -84.47767790640715), 
  c("0452070", "Whitley Family Medical Center", 36.73429314999197, -84.47148955790584), 
  c("0452070", "1515 Edmonton Rd", 36.7222652671451, -85.6894042462668), 
  c("0452070", "McCreary Central Healthy Kids Clinic", 36.70909638222682, -84.46482309534076), 
  c("0452070", "Lincoln County High Healthy Kids Clinic", 37.5126842750625, -84.6556389694152), 
  c("0452070", "285 Education Way", 37.51406348221071, -84.65313066159338), 
  c("0452070", "Stanford Healthy Kids Clinic", 37.54420110493016, -84.67272884624839), 
  c("0452070", "124 Dowell Rd", 37.05790843453787, -85.0654620671169), 
  c("0452070", "404 Steve Dr", 37.0611890721346, -85.07014163091495),
  c("0452070", "404 Steve Drive", 37.0611890721346, -85.07014163091495), 
  c("0452070", "376 Randolph St", 37.31186179300202, -84.9394093818826), 
  c("0452070", "Wayne County Middle Healthy Kids Clinic", 36.82670347562762, -84.86404327324797), 
  c("0452070", "95 Champion Dr", 37.28986187390305, -85.90073639076238),
  c("0452070", "95 Champion Drive", 37.28986187390305, -85.90073639076238), 
  c("0452070", "120 Progress Way", 38.551809766610695, -84.84326233088113), 
  c("0452070", "2258 S HIGHWAY 127", 37.03435605436551, -85.07388315182558),
  c("0452070", "1409 S HIGHWAY 76", 37.07014772502045, -84.98898359466847), 
  
  c("042440", "1551 WEST GOVERNMENT STREET", 32.283036338960585, -90.0222889), 
  c("042440", "1551 W Government St", 32.283036338960585, -90.0222889), 
  c("042440", "1551 West Government Street", 32.283036338960585, -90.0222889), 
  c("042440", "	202 Main Street", 33.74458237747216, -89.37224670214903), 
  c("042440", "1102 Telegraph St", 33.78230646404473, -89.8165613156401), 
  c("042440", "125 School Drive", 31.86215899631174, -89.5515797580054), 
  c("042440", "JEFFERSON STREET", 31.730466402884346, -89.98004088869648), 
  c("042440", "Jefferson Street", 31.730466402884346, -89.98004088869648), 
  c("042440", "4635 HIGHWAY 80 EAST", 32.28277741872335, -90.06309650217774), 
  c("042440", "100 BROOKS AVENUE", 32.31348481651669, -89.79878043101317), 
  c("042440", "910 SECOND STREET", 31.600282956162587, -89.86487557865948),
  c("042440", "4635 Highway 80 E", 32.28277741872335, -90.06309650217774),
  c("042440", "4635 Highway 80 East", 32.28277741872335, -90.06309650217774),
  c("042440", "100 N Brooks St", 32.31348481651669, -89.79878043101317),
  c("042440", "100 Brooks Avenue", 32.31348481651669, -89.79878043101317),
  c("042440", "	65 Morgan Fork Church Ln NW", 31.512637815089874, -90.96198461568405), 
  c("042440", "213 S. County Road, 10-B", 31.846278725811377, -89.39035260218601), 
  c("042440", "	113 Enoch St", 31.115538238451872, -90.14231799056037), 
  c("042440", "130 Lexie Road", 31.068574421385186, -90.15442736142104), 
  c("042440", "102 BLACKMUR DR", 34.150134556080886, -89.6316165733048), 
  c("042440", "118 Front Street", 33.4817118070885, -89.72806655982649), 
  
  c("011210", "1601 Washington Street", 42.338439968230404, -71.07472063078905), 
  c("011210", "39 Bishop Richard Allen Dr", 42.364711397911755, -71.09978335962431), 
  c("011210", "461 Walnut Avenue", 42.3120540185925, -71.09788472374652), 
  c("011210", "170 Morton Street", 42.29948795479483, -71.10169331544564), 
  c("011210", "	38 Broad Street", 42.256456820125365, -70.99444789319953), 
  
  c("040600", "	826 KY 11 N", 37.47943292605277, -83.68943090021695), 
  c("040600", "Owsley County High School Based Clinic", 37.47662663076013, -83.66481405788917), 
  c("040600", "Owsley County Elementary School Based Clinic", 37.476635145181085, -83.6648462443974), 
  c("040600", "72 Buckhorn Clinic Rd", 37.3465187859952, -83.47029541741686),
  c("040600", "72 Buckhorn Clinic Road", 37.3465187859952, -83.47029541741686), 
  c("040600", "464 Ky Highway 699", 37.12230864630958, -83.08676103276609), 
  c("040600", "132 VILLAGE CENTER RD", 36.81591702015666, -83.31705770208437), 
  c("040600", "132 Village Center Rd", 36.81591702015666, -83.31705770208437), 
  c("040600", "269 Highway 3086", 37.161926070048395, -82.6441518658304), 
  c("040600", "105 Isom Plaza", 37.18404852989833, -82.90822518858441), 
  c("040600", "105 Isom Plz", 37.18404852989833, -82.90822518858441), 
  c("040600", "160 Lhs Dr", 37.15459668591515, -82.93460961556855), 
  c("040600", "1540 US Highway 25 E", 36.625880086832225, -83.70330415790812), 
  c("040600", "50 2nd St", 37.19877177846964, -82.70807627487831), 
  c("040600", "435 Cougar Dr.", 37.11936321656515, -82.78970277324152), 
  
  c("060330", "1111 El Llano Rd", 36.00780079894211, -106.03879560210194), 
  c("060330", "1260 Johnny A. Roybal Industrial Park Road", 36.00751583634123, -106.09891112908554), 
  c("060330", "2010 Industrial Park Road", 36.007404694560385, -106.1067157155937), 
  c("060330", "275 NEW MEXICO 3, BUILDING # 2", 35.363707109024645, -105.44953867985855), 
  c("060330", "858 Wagon Mound Hwy", 35.941933282859104, -104.20729536162813), 
  c("060330", "SAN MIGUEL CLINIC", 35.36370561105952, -105.44955384444357), 
  c("060330", "555 Wagon Mound Hwy", 35.94192459666145, -104.20716661559518), 
  c("060330", "585 Wagon Mound Highway", 35.94192459666145, -104.20716661559518), 
  c("060330", "HCNNM San Miguel Clinic", 35.36574219133349, -105.44921503925696), 
  c("060330", "1401 8th St", 36.366286183595456, -104.58272427325801),
  c("060330", "1401 8th Street", 36.366286183595456, -104.58272427325801),
  c("060330", "502 4th St", 36.360754116401516, -104.59692305791303),
  c("060330", "502 4th Street", 36.360754116401516, -104.59692305791303), 
  c("060330", "STATE ROAD 76 STE #60", 36.04385246940241, -105.80822755287669), ## Check this one
  c("060330", "134 Cervantes Road", 36.39286535435112, -105.57515864627403), 
  
  c("04E00055", "100 Panther Way", 36.86884496899548, -83.83276347324716), 
  c("04E00055", "	210 Wall St", 36.86665521185143, -83.89209738289395), 
  c("04E00055", "60 Ky 3441", 36.84959287941804, -83.88670271742787), 
  c("04E00055", "3551 5TH STREET RD", 36.92660001432271, -84.14806110118779), 
  c("04E00055", "200 W 8th St", 36.94270936727291, -84.09716469806663), 
  c("04E00055", "50 Ed Mcneel Dr", 36.95100756436218, -84.08460844440921), 
  c("04E00055", "100 KY 3085", 36.84173752456168, -83.7820086290673), 
  c("04E00055", "138 KY 718", 36.875732838250826, -83.73548628488614), 
  c("04E00055", "101 Creech Hollow Road", 36.80448141878352, -83.74480492486086), 
  c("04E00055", "29 Henderson Settlement Loop", 36.64084752091832, -83.9313046579078), 
  c("04E00055", "39 Cumberland Gap Plaza", 36.950445991702644, -83.98174583062685), 
  c("04E00055", "39 Cumberland Gap Plz", 36.950445991702644, -83.98174583062685), 
  c("04E00055", "12975 Highway 421", 37.067315184846926, -83.40812591557048), 
  c("04E00055", "	272 London Mountain View Dr", 37.15253378673742, -84.11906254440467), 
  c("04E00055", "415 CLAY COUNTY HIGH RD", 37.180461629846334, -83.76576991550799), 
  c("04E00055", "415 Clay County High Rd", 37.180461629846334, -83.76576991550799), 
  c("04E00055", "108 Manchester Shopping Ctr", 37.16155092338808, -83.76732947983552), 
  c("04E00055", "84 Hooker Rd", 37.160435226998416, -83.81801905974886), 
  c("04E00055", "85 Highway 80", 37.13757171287028, -83.76808757324108), 
  c("04E00055", "Grace SBH Burning Springs Elementary", 37.266230208904915, -83.81881043091032) ,
  c("04E00055", "3400 Cumberland Ave", 36.60673843200344, -83.73626658347983), 
  c("04E00055", "4400 W Cumberland Ave", 36.607720260431, -83.74725904997435), 
  c("04E00055", "435 NEWFOUND RD", 37.2712195634612, -83.65164823083741), 
  c("04E00055", "9821 US Highway 25 E", 36.71083851667453, -83.6973696111292), 
  c("04E00055", "9821 US Hwy 25E", 36.71083851667453, -83.6973696111292), 
  c("04E00055", "9824 US Highway 25 E", 36.71371108175333, -83.69208773092261),
  c("04E00055", "9824 US Hwy 25E", 36.71371108175333, -83.69208773092261), 
  c("04E00055", "142 PIRATE DR", 37.183241418302174, -83.30290622412696), 
  c("04E00055", "5923 Highway 80", 37.175692666857124, -83.30513421547315), 
  c("04E00055", "Highway 699", 37.07977952318364, -83.23175640207847), 
  
  c("048980", "17521 W Ky 9", 38.556362862921745, -83.59267597038921), 
  c("048980", "314 RR 2", 38.55886893678556, -83.55592232902838), 
  c("048980", "211 KY 59", 38.5830939084064, -83.3272964746707), 
  c("048980", "116 Laurel School Rd", 38.44322684686623, -83.2654595293169), 
  c("048980", "211 Ky 59 BLDG A", 38.58260509495881, -83.32726752828422), 
  c("048980", "211 Ky 59 BLDG C", 38.58260509495881, -83.32726752828422), 
  c("048980", "211 Ky 59 BLDG D", 38.58260509495881, -83.32726752828422), 
  
  c("082160", "35511 COUNTY ROAD 134", 47.84599838734085, -104.05812912622888), 
  c("082160", "MONTANA MIGRANT COUNCIL, INC.", 47.84599451746268, -104.0580773665469), 
  c("082160", "300 S FINLEY POINT R", 47.73313899963528, -114.05525981715125), 
  c("082160", "300 S FINLEY POINT RD", 47.73313899963528, -114.05525981715125), 
  c("082160", "300 S FINLEY POINT Rd", 47.73313899963528, -114.05525981715125), 
  c("082160", "300 South Finley Point Rd", 47.73313899963528, -114.05525981715125), 
  c("082160", "1015 HWY 200 SOUTH", 48.03262881579217, -115.85950447481487), 
  c("082160", "1414 MAIN STREET", 45.8244059328396, -108.47147672540612), 
  
  c("012030", "Bethel Family Health Center", 44.40977676848716, -70.79137541539069), 
  c("02E01282", "1601 Haddon Ave", 39.92712630195463, -75.0959148596847), 
  c("033030", "Ewing, VA 24248", 36.63475358171404, -83.4345288235142), 
  
  c("014040", "100 CAMPUS DR STE 12", 43.040119675907576, -70.786899988443), 
  c("014040", "100 Campus Dr STE 12", 43.040119675907576, -70.786899988443), 
  c("014040", "100 Campus Dr", 43.040119675907576, -70.786899988443),
  c("014040", "	100 Campus Drive, Suite 12", 43.040119675907576, -70.786899988443), 
  
  c("047330", "502 SOUTH PARK AVENUE", 31.23562213984167, -89.82278319668556),
  c("047330", "502 South Park Avenue", 31.23562213984167, -89.82278319668556), 
  c("047330", "101 Hospital Drive", 31.11976816220088, -90.15571735987169), 
  c("047330", "101 HOSPITAL DRIVE", 31.11976816220088, -90.15571735987169), 
  
  c("0452880", "1706 Highland Ave", 38.683182097695266, -85.15665864436988),
  c("0452880", "1708 Highland Ave", 38.68472799014945, -85.15824192043868), 
  c("0452880", "329 Floyd Dr", 38.65942989571101, -85.13281332305336), 
  c("0452880", "329 Floyd Dr Ste A", 38.65942989571101, -85.13281332305336), 
  c("0452880", "329 Floyd Dr Ste E", 38.65942989571101, -85.13281332305336), 
  c("0452880", "519 Park Ave", 38.67922075390357, -85.15824508855029),
  c("0452880", "519 Park Ave.", 38.67922075390357, -85.15824508855029), 
  c("0452880", "619 9th St", 38.67435966580174, -85.1720698462226), 
  c("0452880", "619 Ninth St", 38.67435966580174, -85.1720698462226), 
  c("0452880", "907 Hawkins St", 38.67462444475299, -85.17122567777172), 
  c("0452880", "1005 HIGHWAY 22 E", 38.52788707403818, -84.8243727790636), 
  c("0452880", "120 Progress Way", 38.55181815704188, -84.84328378855328), 
  c("0452880", "1925 Highway 22 E", 38.530928057821264, -84.86788995971763), 
  c("0452880", "1925 US HWY 22 East", 38.530928057821264, -84.86788995971763), 
  c("0452880", "1945 HWY 22 E", 38.523460434304624, -84.81522671553748),
  c("0452880", "1945 Highway 22 E", 38.523460434304624, -84.81522671553748), 
  c("0452880", "Owen County Elementary School", 8.523460434304624, -84.81522671553748), 
  c("0452880", "Owen County High School", 38.523343617285015, -84.81490664023862),
  c("0452880", "Owen Co High School NEW", 38.53013250350217, -84.80829672561536), 
  c("0452880", "Owen County Dental", 38.54244846170021, -84.84116211553705), 
  c("0452880", "Maurice Bowling Middle School", 38.530267966093184, -84.80563390204556), 
  c("0452880", "25 Boaz Dr", 38.78330622207465, -84.89385018854793), 
  c("0452880", "50 Pawprint Path", 38.78539472905228, -84.89231807320351), 
  c("0452880", "70 Wildcat Cir", 38.78622482769985, -84.88897284066235), 
  c("0452880", "88 Pawprint Path", 38.78529829227777, -84.89097505936924), 
  
  c("0622460", "415 6th St", 34.583547903802,	-95.3599617543302), 
  c("0622460", "109 STANLEY ROAD", 34.58616830066575, -95.35482627329586), 
  c("0622460", "1020 N Lawson Blvd", 34.60020611234506, -95.34302526459228),
  c("0622460", "1020 North Lawson Blvd", 34.60020611234506, -95.34302526459228), 
  c("0622460", "109 Stanley Road", 34.58616830066575, -95.35482627329586)
  
  )

geocoded.by.hand <- data.frame(geocoded.by.hand) %>% 
  rename(BHCMIS.ID = X1, add = X2, lat = X3, long = X4)


sites.hand %>% 
  filter(BHCMIS.ID == "0622460") %>% 
  arrange(Site.City, Site.Street.Address, Site.Street.Address.2, Site.Street.Address.3) %>% 
  select(lat, long, Site.Name:Zip)

```




## Put It together

```{r}



sites.hand <- rbind(sites.hand %>% 
    filter(!is.na(lat)),sites.hand %>% 
    filter(is.na(lat)) %>% 
    left_join(geocoded.by.hand, by = c("BHCMIS.ID", "Site.Street.Address" = "add")) %>% 
    left_join(geocoded.by.hand, by = c("BHCMIS.ID", "Site.Street.Address.2" = "add")) %>% 
    left_join(geocoded.by.hand, by = c("BHCMIS.ID", "Site.Street.Address.3" = "add")) %>% 
      
     mutate(lat = ifelse(!is.na(lat.x), lat.x, 
                        ifelse(is.na(lat.x) & !is.na(lat.y), lat.y, 
                               ifelse(is.na(lat.x) & is.na(lat.y) & !is.na(lat.x.x), lat.x.x, 
                                      ifelse(is.na(lat.x) & is.na(lat.y) & is.na(lat.x.x), lat.y.y, NA)))),
         long = ifelse(!is.na(long.x), long.x, 
                        ifelse(is.na(long.x) & !is.na(long.y), long.y, 
                               ifelse(is.na(long.x) & is.na(long.y) & !is.na(long.x.x), long.x.x, 
                                      ifelse(is.na(long.x) & is.na(long.y) & is.na(long.x.x), long.y.y, NA))))) %>% 
    select(BHCMIS.ID:Zip, lat, long)
) %>% filter(Site.State != 'AK' & Site.State != 'HI') %>% 
  left_join(geocoded.by.hand, by = c("BHCMIS.ID", "Site.Name" = "add")) %>% 
  mutate(lat = ifelse(!is.na(lat.x), lat.x, lat.y), 
         long = ifelse(!is.na(long.x), long.x, long.y)) %>% 
  select(BHCMIS.ID:Zip, lat, long)


nrow(sites.hand %>% filter(is.na(lat))) / nrow(sites.hand )



todo <- table((sites.hand[is.na(sites.hand$lat),]$BHCMIS.ID))[order(table((sites.hand[is.na(sites.hand$lat),]$BHCMIS.ID)), decreasing = T)]



todo.alt <- todo[order(names(todo))] / table(sites.hand[sites.hand$BHCMIS.ID %in% names(todo),]$BHCMIS.ID)

todo.alt[order(todo.alt, decreasing = T)]

```


## Write Temp
```{r}
#write.csv(x = sites.hand, file = "/Users/markow/Dropbox/Git/Allocation/data_processed/sites_nintypercent_geocoded.csv", row.names = FALSE)
```









# Map - missing 1998 data
```{r}

eq_transformed <- usmap_transform(data = sites.coded  %>% mutate(lon = as.numeric(ifelse(is.na(long), long.1, 
                                                                                  ifelse(is.na(long) & is.na(long.1), long.2, long))), 
                                                                 lat = as.numeric(ifelse(is.na(lat), lat.1, 
                                                                                  ifelse(is.na(lat) & is.na(lat.1), lat.2, lat)))) %>% filter(!is.na(lat))) %>% 
  mutate(year = as.numeric(Year)) %>% 
  arrange(BHCMIS.ID, Site.Name, Year) %>% 
  filter(Year >= 1999) %>% 
  filter(Site.State %in% c("CT","RI","MA","NH","VT","ME"))
  #filter(Site.State %in% c("IL","IN","WI","MN","IA","MO","OH","MI"))


grafico <- plot_usmap(include = c("CT","RI","MA","NH","VT","ME")) +
  geom_point(data = eq_transformed, aes(x = x, y = y, col = Site.State), size = 0.5) +
  labs(title = "FQHC Care Delivery Location Growth",
       subtitle = "1999 - 2021") +
  theme(legend.position = "right")
```


```{r}

p <- grafico +
  transition_time(year) +
  labs(title = "FQHC Growth by Year: {frame_time}")

p <- animate(p, nframes = length(1999:2021), fps = 4)

anim_save("/Users/jhm65/Dropbox/Git/Allocation/visuals/growth.gif", p)

p
```














